import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

const noto = Noto_Sans({
  weight: ["300", "400", "500", "700"],
  style: ['normal', 'italic'],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "dferandad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
