import type { Metadata } from "next";
import { Footer, Header, Sidebar } from "@/components";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const noto = Noto_Sans({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Reviews App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <main className={styles.main}>{children}</main>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
